### ISSUE TITLE
Dúvida em qual branch mandar o PR

### ISSUE THREAD

**Issue by barbozafernando** [eguatech/docs#28]
Boa tarde, @lucaspompeun. Vi que não tem a branch `desenvolvimento`. Segundo o Jazancort, o servidor em produção pega direto da branch `hostgator`, correto?

**Comment by lucaspompeun** [comment]
Isso, aqui o esquema é diferente. Manda pra master que o Travis CI e o GH Actions vão buildar, mandar para branch hostgator e atualizar no servidor.
