### ISSUE TITLE
Revisar a doc do eguap

### ISSUE THREAD

**Issue by gabrielloliveira** [eguatech/docs#4]
Olá caros amigos, encontrei o projeto num canal do telegram. Gostei bastante do projeto (bem melhor do que usar portugol para quem está começando! e nem precisa baixar nada. egua >>> portugol)

Alguns exemplos de código não estão condizentes com a linguagem, ex:
![Captura de Tela 2020-05-04 às 12 51 45](https://user-images.githubusercontent.com/19738500/80987258-2d5a5a00-8e08-11ea-93aa-85b58d43dbd0.png)
** um else solto no meio de codigo na linguagem egua.

Também existe um exemplo onde não foi postado todo o código de saída:
![Captura de Tela 2020-05-04 às 12 52 34](https://user-images.githubusercontent.com/19738500/80987416-64307000-8e08-11ea-9a0f-7f1892d7e73b.png)
** o certo seria "Hello World, or, Hello Egua" 
** ainda acho que seria mais interessante deiar tudo em português, já que é o diferencial. Então poderia ser "Olá mundo, ou Olá Egua"

**Comment by lucaspompeun** [comment]
Todas as sinalizações foram revisadas e corrigidas
