### ISSUE TITLE
Adicionar o próprio egua highlight 

### ISSUE THREAD

**Issue by gabrielloliveira** [eguatech/docs#5]
Poderia ser feito um próprio highlight. Mesmo que seja mais custoso e estressante, para o aluno iniciante (acredito que o projeto seja pra esse público) é mais interessante ele ver um highlight da linguagem egua.

Ex. comando escreva deveria ter uma cor de destaque, pois é palavra reservada.
![Captura de Tela 2020-05-04 às 12 52 34](https://user-images.githubusercontent.com/19738500/80988126-68a95880-8e09-11ea-8583-6d227135cc94.png)

**Comment by lucaspompeun** [comment]
Opa, @gabrielloliveira. Agradecemos sua contribuição pra gente. Estamos com planos para criação de um highlight de sintaxe do egua. Levará alguns dias para isso entrar em produção na documentação, assim como a identificação da linguagem egua no github, visto que há a necessidade de alguns requisitos mínimos pra isso.
Agradeço novamente sua contribuição e manteremos essa issue aberta para devido acompanhamento da inclusão desta nova feature.

**Comment by gabrielloliveira** [comment]
Que massa @lucaspompeun 😄
Gostei bastante da linguagem e achei muito legal a iniciativa.  

Forte abraço.

**Comment by lucaspompeun** [comment]
Verificamos que a viabilidade dessa issue não existe :(
O vuepress, que é o static site generator que usamos não possui como alterar o syntax highlight, portanto precisarei fechar a issue e torcer pra que um dia isso seja possível.

Agradecemos a sua preocupação e esperamos que esteja curtindo a linguagem
