### ISSUE TITLE
Adicionar seção ensinando sobre comentários

### ISSUE THREAD

**Issue by samuelrvg** [eguatech/docs#50]
Pelos meus testes, tem somente comentário simples com "//" testei "/* */" para multiplas linhas, mas parece não ter suporte ainda.

Logo, adicionar na doc uma breve explicação de como fazer, acredito ser válido.

**Comment by lucaspompeun** [comment]
Adicionado
![image](https://github.com/eguatech/docs/assets/8001253/37ff4243-ff8b-4424-aeff-6cfb4bfb1fc5)
