### ISSUE TITLE
Erro 404: Conteúdo não encontrado

### ISSUE THREAD

**Issue by RenatoExpert** [eguatech/docs#77]
# Descrição
O conteúdo do site não está aparecendo
# Prints
## Navegando no site
![image](https://user-images.githubusercontent.com/20760510/210664697-47707688-1953-4f8e-b462-2f80dcec791c.png)
## No console (devtools) do chrome
![image](https://user-images.githubusercontent.com/20760510/210664640-bec13391-a0bd-4980-8ec0-b2938c4eb67c.png)

**Comment by lucaspompeun** [comment]
Onde você encontrou o link para a introdução? Ela foi retirada do site, pois tinha informações repetitivas que já estavam em outros lugares do site. 
Caso algum lugar dentro de algum site da linguagem tenha te levado a este link, me avisa que eu já resolvo.

**Comment by RenatoExpert** [comment]
Não lembro onde cliquei no dia que fiz esse issue, mas procurando agora, encontrei esse botao
![image](https://user-images.githubusercontent.com/20760510/210881838-3d052177-019f-42a9-9b4b-aad678c60efe.png)

**Comment by lucaspompeun** [comment]
Corrigido
