### ISSUE TITLE
Link do grupo do Whatsapp não funciona

### ISSUE THREAD

**Issue by RenatoExpert** [eguatech/docs#78]
Queria entrar no grupo do whatsapp, mas o link parece estar desatualizado :(

### Print
![image](https://user-images.githubusercontent.com/20760510/210665257-9fc674ab-0ac4-466b-b2b5-f94c61d7d74c.png)

**Comment by RenatoExpert** [comment]
Vou deixar uma sugestão:
Pra não precisar ficar atualizando o link no código fonte do site, pode colocar um subdominio CNAME, por exemplo `whatsapp.egua.tech`, e ai basta atualizar o dominio.

**Comment by lucaspompeun** [comment]
O grupo na verdade foi excluído há alguns meses, onde você encontrou ele para que eu possa corrigir?

**Comment by RenatoExpert** [comment]
Poxa, que pena que não existe mais! Eu gostaria muito de contribuir com o projeto, e acho que o whatsapp acaba sendo um dos meios mais praticos.
Eu encontrei o link nessa pagina https://egua.tech/comunidade

**Comment by lucaspompeun** [comment]
Corrigido
